name: Update ASN and IP List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

concurrency:
  group: update-asn-list
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: MetaCubeX/meta-rules-dat
          ref: meta
          path: meta-rules-dat
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: |
          npm ci --omit=dev
          rm -rf data country

      - name: Install mihomo
        run: |
          version=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/v${version}/mihomo-linux-amd64-v3-v${version}.gz" | \
            gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo
          
      - name: Install singbox
        run: |
          version=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -sL "https://github.com/SagerNet/sing-box/releases/download/v${version}/sing-box-${version}-linux-amd64.tar.gz" | \
            tar -xz -C /usr/local/bin --strip-components=1 sing-box-${version}-linux-amd64/sing-box && chmod +x /usr/local/bin/sing-box

      - name: Update ASN and IP List country
        run: npm run generate

      - name: Validate generated data
        run: npm test

      - name: Update data and mihomo IP List country
        run: node scripts/mihomo.js
        env:
          base_dir: data

      - name: Update country and mihomo IP List country
        run: node scripts/mihomo.js
        env:
          base_dir: country

      - name: Delete build dependencies
        run: rm -rf meta-rules-dat

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update IP List
